# Generated by Django 4.1.2 on 2023-03-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_image_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/products/main'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_caption',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='images/products/thumbnails'),
        ),
    ]
