# Generated by Django 4.1.2 on 2023-03-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_image_alter_product_image_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_caption',
            new_name='image_caption1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail',
            new_name='thumbnails',
        ),
    ]
