# Generated by Django 4.1.2 on 2023-03-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_image_caption_product_image_caption1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_caption2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail2',
            field=models.ImageField(blank=True, upload_to='images/products/thumbnails'),
        ),
    ]
