# Generated by Django 4.1.2 on 2023-03-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_caption1',
            new_name='image_caption',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_caption2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail2',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/products/main'),
        ),
    ]
