# Generated by Django 4.1.2 on 2023-03-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='tracking_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
