# Generated by Django 4.1.2 on 2023-03-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchterm_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchterm',
            name='tracking_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
